In [ ]:
#part1：创建指定数组和处理形式

In [7]:
import numpy as np
#把numpy作为np导入了，接下来就能直接用这个库中的函数

In [8]:
arr1=np.array([1,2,3])
print(arr1)
#array是np库中的一个函数

[1 2 3]


In [9]:
arr2=arr1.astype(float)
print(arr2)
#转化数组类型，int转float
#以后要换数据类型另起一行加一步.astype()就可以了

[1. 2. 3.]


In [10]:
arr3=arr1.reshape(3,1)
print(arr3)
#对数组进行升维

[[1]
 [2]
 [3]]


In [11]:
arr4=arr3.reshape(-1)
print(arr4)
#还是用reshape降维，直接写-1很方便就是让它自己算剩下的参数（不是实际含义而是功能含义）or用reshape写成万能目标维数即可

[1 2 3]


In [13]:
#创建二维数组的行/列矩阵
arr2=np.array([[1,2,3]])
arr3=np.array([[1],[2],[3]])
print(arr2)
print(arr3)
#二维数组肯定要包两个[]的，但是怎么包就决定了其是行/列矩阵——写在一起就默认行

[[1 2 3]]
[[1]
 [2]
 [3]]


In [14]:
#创建递增数组

In [15]:
arr1=np.arange(10)   #从0开始，到10之前结束（还是那个左闭右开原则）
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
arr2=np.arange(10,20)  #从10开始，到20之前结束
print(arr2)

[10 11 12 13 14 15 16 17 18 19]


In [18]:
arr3=np.arange(1,21,2)  #从1开始，到21之前结束，步长为2
print(arr3)

[ 1  3  5  7  9 11 13 15 17 19]


In [19]:
#创建同值数组

In [20]:
#全0数组
arr1=np.zeros(3)  #形状为3的向量，同样如果传1，3就会得到一个行矩阵
print(arr1)

[0. 0. 0.]


In [22]:
#全1数组
arr2=np.ones((2,3))  #注意还要再包个括号表示生成矩阵；外面那个括号指的是函数的括号
print(arr2)

[[1. 1. 1.]
 [1. 1. 1.]]


In [23]:
#别的全值数组（如3.14）
arr3=3.14*np.ones((2,3))  #在外面×一下就行
print(arr3)

[[3.14 3.14 3.14]
 [3.14 3.14 3.14]]


In [24]:
#创建随机数组——np.random()函数
#详情见笔记pdf

In [25]:
#part2：访问数组元素

In [26]:
#part3：数组切片——用“：”
#🔺跳跃采样（ML常用）
#数组提取——还是用“：”，但切片在前，提取在后，中间用“，”隔开

In [27]:
#注意：为了节约内存对两个数组直接取等还是共用一个内存，要想使它们相互独立互不影响只能使用.copy

In [28]:
#part4：数组的变形

In [30]:
#用.T进行矩阵的转置————向量要先转为矩阵才能.T
arr1=np.arange(3).reshape(3,1)  #创建列矩阵
print(arr1)

[[0]
 [1]
 [2]]


In [31]:
arr2=arr1.T
print(arr2)

[[0 1 2]]


In [32]:
#🔺数组的翻转（ML常用）
#上下翻转是np.flipud()；左右翻转是np.fliplr()————其中向量只能使用前者，解释分别是up&down以及left&right

In [33]:
#向量翻转
arr1=np.arange(10)
arr_ud=np.flipud(arr1)
print(arr_ud)

[9 8 7 6 5 4 3 2 1 0]


In [34]:
#矩阵翻转
arr2=np.arange(1,21).reshape(4,5)
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [35]:
#左右翻转
arr_lr=np.fliplr(arr2)
print(arr_lr)

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]
 [20 19 18 17 16]]


In [36]:
#上下翻转
arr_ud=np.flipud(arr2)
print(arr_ud)

[[16 17 18 19 20]
 [11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]


In [37]:
#数组拼接：使用np.concatenate([数组名1，数组名2])函数——————拼接前要确保同维度

In [38]:
#数组分裂：使用np.split(数组名，[参数1，参数2])——————参数1和参数2就是表示在第几个空位处砍一刀

In [39]:
arr=np.arange(10,100,10)
print(arr)

[10 20 30 40 50 60 70 80 90]


In [40]:
#分裂数组
arr1,arr2,arr3=np.split(arr,[2,8])   #表示从第2，8个空砍一刀，且要拿新数组去接
print(arr1)
print(arr2)
print(arr3)

[10 20]
[30 40 50 60 70 80]
[90]


In [41]:
#分裂矩阵
arr=np.arange(1,9).reshape(2,4)
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [44]:
#按照第一个维度（行）进行分裂
arr1,arr2=np.split(arr,[1])          #这里第三个参数没写是默认了axis=0：即按行分裂
print(arr1,'\n\n',arr2)              #python中换行符\n的实现是字符串（老是忘记）

[[1 2 3 4]] 

 [[5 6 7 8]]


In [46]:
#按照第二个维度（列）进行分类
arr1,arr2,arr3=np.split(arr,[1,3],axis=1)   #表示从列的第1，3个空分裂
print(arr1,'\n\n',arr2,'\n\n',arr3)

[[1]
 [5]] 

 [[2 3]
 [6 7]] 

 [[4]
 [8]]


In [47]:
#part5：数组运算——即对应元素间的运算
#如果要实现线代中的矩阵乘法则要借鉴下一part中的函数

In [48]:
#如果某行/列矩阵与一般的矩阵进行运算，它就会被广播用来适配另一个矩阵
arr1=np.arange(3).reshape(3,1)
print(arr1)

[[0]
 [1]
 [2]]


In [49]:
arr2=np.ones((3,5))
print(arr2)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [50]:
#广播
print(arr1*arr2)

[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]]


In [51]:
#part6：数组的函数

In [53]:
#矩阵乘法函数：np.dot()
#注意要符合矩阵乘法的运算法则
#当混有向量时输出结果就是向量（向量和单行/列的矩阵还是差了个[]的）

In [54]:
#e.g.:向量形状为5，矩阵形状为(5,3)，故结果应该是(1,5)×(5,3)=(1,3)形状为3的向量
arr1=np.arange(5)
arr2=np.arange(15).reshape(5,3)
print(arr1)
print(arr2)

[0 1 2 3 4]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [55]:
#矩阵乘法
print(np.dot(arr1,arr2))
#矩阵和矩阵相乘以此类推

[ 90 100 110]


In [56]:
#数学函数：
#绝对值函数：np.abs()
#三角函数：np.sin/cos/tan()
#指数函数：np.exp()是有关e的 & 一般的用运算符**即可
#对数函数：np.log ———— 想表示以2为底就换底公式，如np.log(x)/np.log(2)

In [59]:
#🔺聚合函数

In [60]:
#最大/最小值函数:np.max()/np/min()  ——————  可以通过axis参数来比数组的行和列

In [61]:
arr=np.random.random((2,3))
print(arr)

[[0.29671438 0.11643891 0.05000038]
 [0.96718412 0.48750066 0.18845598]]


In [62]:
print('按维度一求最大值：',np.max(arr,axis=0))    #这里axis=0表示的不是比较行的最大值了，是以行的视角去一个个比较列的max最终得到一行的结果

按维度一求最大值： [0.96718412 0.48750066 0.18845598]


In [64]:
print('按维度二求最大值：',np.max(arr,axis=1))

按维度二求最大值： [0.29671438 0.96718412]


In [65]:
print('整体求最大值：',np.max(arr))   

整体求最大值： 0.9671841170002258


In [66]:
#求和函数np.sum()
#求积函数np.prod()

In [67]:
arr=np.arange(10).reshape(2,5)
print(arr)
print('按维度一求和：',np.sum(arr,axis=0))         #以行的视角一列列去加和
print('按维度二求和：',np.sum(arr,axis=1))
print('整体求和：',np.sum(arr))

[[0 1 2 3 4]
 [5 6 7 8 9]]
按维度一求和： [ 5  7  9 11 13]
按维度二求和： [10 35]
整体求和： 45


In [68]:
#均值函数np.mean()
#标准差函数np.std()
#应用与上一致

In [69]:
#skills：当axis=0时，最终结果与每一行的元素个数一致
#        当axis=1时，最终结果与每一列的元素个数一致

In [70]:
#part7：布尔型数组
#实现方式：与index作比较；同维数组之间作比较
#意义如下：1.判断数组元素关系  2.作为index筛选(掩码)

In [ ]:
#np.any()函数————只要布尔型数组里有一个及其以上的True就返回True
#np.all()函数——当布尔型数组全是True时才返回True

In [72]:
arr1=np.arange(1,10)
arr2=np.flipud(arr1)
print(arr1)
print(arr2)
#统计这两个数组里是否有共同元素
print(np.any(arr1==arr2))

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]
True


In [73]:
arr=np.random.normal(500,70,10000)
print(np.all(arr>250))   #判断是否所有的数据都大于250

False


In [74]:
#以布尔型数组作为index（掩码）筛选符合条件的元素——————最重要的功能
arr=np.arange(1,13).reshape(3,4)
print(arr)
print(arr>4)  #arr>4已经是一个新的布尔型数组了
print(arr[arr>4])
#布尔数组的每个布尔值（True/False）与原数组的每个元素一一对应
#注意：对矩阵进行掩码操作后退化为了向量

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]
[ 5  6  7  8  9 10 11 12]


In [75]:
#想知道满足某个条件的元素们所在的索引位置————使用np.where()函数

In [76]:
#模拟英语六级成绩的随机数组，取10000个样本
arr=np.random.normal(500,70,10000)

In [78]:
#找出六级成绩超过650的元素所在位置
print(np.where(arr>650))

(array([  21,   84,  195,  197,  278,  336,  348,  417,  445,  516,  600,
        726,  780,  811,  926, 1116, 1136, 1232, 1245, 1298, 1523, 1585,
       1591, 1593, 1604, 1612, 1636, 1674, 1698, 1779, 1907, 2036, 2082,
       2126, 2230, 2253, 2361, 2454, 2531, 2553, 2644, 2763, 2778, 2830,
       2861, 2913, 2988, 3013, 3018, 3075, 3130, 3138, 3298, 3367, 3404,
       3415, 3535, 3706, 3745, 3805, 3849, 3910, 4098, 4102, 4128, 4160,
       4190, 4248, 4293, 4329, 4346, 4403, 4405, 4447, 4450, 4549, 4694,
       4707, 5155, 5167, 5175, 5279, 5302, 5493, 5596, 5696, 5818, 5868,
       5871, 5989, 6014, 6167, 6193, 6199, 6297, 6300, 6464, 6490, 6511,
       6524, 6561, 6866, 6961, 6984, 7122, 7124, 7150, 7230, 7262, 7369,
       7385, 7422, 7429, 7523, 7535, 7575, 7603, 7728, 7736, 7789, 7828,
       7838, 7971, 8126, 8182, 8208, 8220, 8237, 8269, 8276, 8354, 8356,
       8397, 8460, 8461, 8466, 8479, 8484, 8524, 8643, 8678, 8877, 9009,
       9110, 9135, 9165, 9194, 9344, 9404, 9538, 9

In [79]:
#找出六级成绩最高分的元素位置
print(np.where(arr==np.max(arr)))  #np.max(arr)是标量就是唯一的那个最大值

(array([4190], dtype=int64),)


In [80]:
#part8：数组-张量

In [81]:
#numpy与pytorch的基础语法几乎一致，体现为：
#1.np对应torch
#2.数组array对应张量tensor
#3.numpy的n维数组对应pytorch的n维张量

In [ ]:
#finish！！！